accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.welcome, name='welcome'),
]

farm_products/urls.py
from django.urls import path
from . import views

app_name = 'farm_products'
urlpatterns = [
    path('', views.show_graph, name='graph'),
    path('test/', views.test, name='test'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('farm_products/', include('farm_products.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

farm_products/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.
def welcome(request):
    return render(request, 'accounts/welcome.html')

farm_products/views.py
from django.shortcuts import render

import io
import urllib, base64
import pandas as pd
import matplotlib.pyplot as plt
from .kamis import kamis

# Create your views here.
def test(request):
    if request.method == 'POST':
        context = {
            'method':'post'
        }
    else:
        context = {
            'method':'get'
        }
    return render(request, 'farm_products/test.html', context)


def show_graph(request):
    uri = ""
    region = {1101:'서울', 2100:'부산', 2200:'대구', 2300:'인천', 2401:'광주', 2501:'대전', 2601:'울산', 3111:'수원', 3211:'춘천', 3311:'청주', 3511:'전주', 3711:'포항', 3911:'제주', 3113:'의정부', 3613:'순천', 3714:'안동', 3814:'창원', 3145:'용인'}
    if request.method == 'POST':
        kwargs = {'action':'monthlySalesList', 'p_returntype':'json'}
        kwargs['p_itemcode'] = request.POST['item']
        kwargs['p_yyyy'] = '2020'
        kwargs['p_period'] = '3'
        try:
            kwargs['p_kindcode'] = request.POST['variety']
        except: pass
        try:
            kwargs['p_graderank'] = request.POST['p_graderank']
        except: pass
        if request.POST['region'] != 'on':
            kwargs['p_countycode'] = request.POST['region']
        # data 불러오기
        response = kamis(**kwargs)
        plt.figure()
        data = {}
        for item in response['price'][0]['item']:
            data[item['yyyy']] = [(0 if (value == '-') else int(value.replace(',', ''))) for value in item.values()][1:-1]
        df = pd.DataFrame(data)

        all_data = pd.concat([df.loc[:, column] for column in df.columns], axis=0, ignore_index=True)
        plt.plot(all_data)
        fig = plt.gcf()
        buf = io.BytesIO()
        fig.savefig(buf, format='png')
        buf.seek(0)
        string = base64.b64encode(buf.read())
        uri = urllib.parse.quote(string)

    # 품목코드 data 불러오기
    code = pd.read_excel('./Portfolio/code.xls', sheet_name='코드통합(부류＋품목＋품종코드)')
    code_set = {}
    for i in range(code.shape[0]):
        if code.iloc[i, 0] not in code_set:
            code_set[code.iloc[i, 0]] = {'name':code.iloc[i, 1]}
        if code.iloc[i, 2] not in code_set[code.iloc[i, 0]]:
            code_set[code.iloc[i, 0]][code.iloc[i, 2]] = {'name':code.iloc[i, 3]}
        if code.iloc[i, 4] not in code_set[code.iloc[i, 0]][code.iloc[i, 2]]:
            code_set[code.iloc[i, 0]][code.iloc[i, 2]][code.iloc[i, 4]] = {'name':code.iloc[i, 5]}
    context = {
        'data':uri,
        'regions': region,
        'code_set':code_set,
    }
    return render(request, 'farm_products/index.html', context)

accounts/templates/accounts/welcome.html
{% extends 'base.html' %}

{% block content %}
    <h1 class='text-center mt-4'>Welcome to my page!</h1>
{% endblock content %}

farm_products/templates/farm_products/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center">그래프 화면</h1>
  <form action="" method="post">
  {% csrf_token %}
    <div class="d-flex justify-content-around">
      <!-- 지역 -->
      <div id="regions" class="btn-group btn-group-toggle d-flex flex-column" data-toggle="buttons">
        <label class="btn btn-light">
          <input type="radio" name="region"> 전체
        </label>
        {% for region in regions.items %}
          <label class="btn btn-light">
            <input type="radio" name="region" value="{{ region.0 }}"> {{ region.1 }}
          </label>
        {% endfor %}
      </div>

      <!-- 부류 -->
      <div id="categorys" class="btn-group btn-group-toggle d-flex flex-column" data-toggle="buttons">
      </div>

      <!-- 품목 -->
      <div id="items" class="btn-group btn-group-toggle d-flex flex-column" data-toggle="buttons">
      </div>

      <!-- 품종 -->
      <div id="varietys" class="btn-group btn-group-toggle d-flex flex-column" data-toggle="buttons">
        <label class="btn btn-light active">
          <input type="radio" checked> 전체
        </label>
      </div>

      <input class="btn btn-primary" type="submit" value="submit">
    </div>
  </form>
  <img src="data:image/png;base64,{{ data }}" class="img-fluid" alt="">
  <h3>세로축: (원) 가로축: (개월)</h3>

  <script>
    const regions = document.querySelector("#regions").querySelectorAll('input')
    regions[0].checked = true

    const code_set = {{code_set|safe}}

    // categry 버튼리스트 만들기
    const categorys = document.querySelector("#categorys")
    for (i in code_set) {
      const input = document.createElement("input")
      input.type = "radio"
      input.name = "category"
      input.value = i
      const label = document.createElement("label")
      label.classList.add("btn", "btn-light")
      label.innerText = code_set[i].name
      label.appendChild(input)
      categorys.appendChild(label)
    }
    categorys.querySelector("input").parentNode.classList.add("active")
    categorys.querySelector("input").checked = true
    // 카테고리 눌렀을때 로직
    function recog_items() {
      // category 눌린버튼 찾기
      category_inputs = categorys.querySelectorAll("input")
      for (var i=0; i < category_inputs.length; i++) {
        if (category_inputs[i].parentNode.classList.contains("active") == true) {
          category = code_set[category_inputs[i].value]
        }
      }

      // item 버튼리스트 만들기
      const items = document.querySelector("#items")
      items.innerText = ""
      for (i in category) {
        if (i == 'name') {
          break
        }
        const input = document.createElement("input")
        input.type = "radio"
        input.name = "item"
        input.value = i
        const label = document.createElement("label")
        label.classList.add("btn", "btn-light")
        label.innerText = category[i].name
        label.appendChild(input)
        items.appendChild(label)
      }
      items.querySelector("input").parentNode.classList.add("active")
      items.querySelector("input").checked = true
      recog_varietys.call()
    }

    // item 눌렀을때 로직
    function recog_varietys() {
      // item 눌린버튼 찾기
      items_inputs = items.querySelectorAll("input")
      for (var i=0; i < items_inputs.length; i++) {
        if (items_inputs[i].parentNode.classList.contains("active") == true) {
          item = category[items_inputs[i].value]
        }
      }

      // variety 버튼리스트 만들기
      const varietys = document.querySelector("#varietys")
      varietys.innerHTML = '<label class="btn btn-light active"> <input type="radio" checked> 전체</label>'
      for (i in item) {
        if (i == 'name') {
          break
        }
        const input = document.createElement("input")
        input.type = "radio"
        input.name = "variety"
        if (i.length == 1) {
          console.log(i)
          input.value = `0${i}`
        } else {
          input.value = i
        }
        const label = document.createElement("label")
        label.classList.add("btn", "btn-light")
        label.innerText = item[i].name
        label.appendChild(input)
        varietys.appendChild(label)
      }
    }

    document.addEventListener("DOMContentLoaded", recog_items)
    document.addEventListener("DOMContentLoaded", function () {
    })

    categorys.addEventListener("click", recog_items)
    items.addEventListener("click", recog_varietys)

  </script>
{% endblock content %}

farm_products/templates/farm_products/test.html
{% extends 'base.html' %}

{% block content %}
{{ method }}
<form action="" method="post">
  {% csrf_token %}
  <input type="submit" value="submit">
</form>
{% endblock content %}

portfolio/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% bootstrap_css %}
  <title>hojp7874</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'farm_products:graph' %}">Farm product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown link
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>
  {% bootstrap_javascript jquery='full' %}
</body>
</html>